# Generated by Django 4.0.4 on 2023-02-12 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_price', models.IntegerField()),
                ('book_status', models.BooleanField()),
                ('book_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
