# Generated by Django 4.0.4 on 2023-02-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_visitors_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_issue',
            old_name='book_id',
            new_name='book_name',
        ),
    ]
